### ISSUE TITLE
Hay un bug al intentar girar la pelota con pygame.transform.rotate

### ISSUE THREAD

**Issue by antonio0219** [team-frog/Question#2]
# AQUÍ DEJO UNOS ENLACES PARA AYUDAR A SOLUCIONARLO
https://www.pygame.org/docs/ref/transform.html#pygame.transform.rotate
https://stackoverflow.com/questions/28261163/out-of-memory-when-using-pygame-transform-rotate

**Comment by FernandoMCh** [comment]
Al rotar una imagen cambia el rectángulo de la misma, porque no rota respecto al centro.
Había que hacer get_rect de la imagen, y posicionar el centro a x,y
